# docker-compose.yml
services:
  postgres:
    image: postgres:17
    container_name: whiteboard-postgres
    environment:
      POSTGRES_DB: whiteboard
      POSTGRES_USER: whiteboard_user
      POSTGRES_PASSWORD: whiteboard_pass
    ports:
      - "5432:5432"
    volumes:
      - whiteboard_pg_data:/var/lib/postgresql/data

volumes:
  whiteboard_pg_data: